### ISSUE TITLE
Change DEFAULTS to inital

### ISSUE THREAD

**Issue by vitalbone** [dvbsknd/freeCodeCamp-frontEndProjects#2]
https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L63

The term `DEFAULTS` is confusing here. `DEFAULTS` usually refers to a constant, unchanging value. I think what you're after here is an initial value. Again, probably best to namespace it to the clock.

**Comment by dvbsknd** [comment]
Agree! Will amend.
