### ISSUE TITLE
Change 60 to constant value

### ISSUE THREAD

**Issue by vitalbone** [dvbsknd/freeCodeCamp-frontEndProjects#3]
https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L108

Between lines 108 - 140 there are a lot of references to `60`. Best to create a constant variable, something like `ONE_SEC = 60` and replace all instances. Better readability and easier to change, if you decide to change the duration for whatever reason.

**Comment by dvbsknd** [comment]
Great idea, will do.
