### ISSUE TITLE
Props should be as "dumb" as possible

### ISSUE THREAD

**Issue by vitalbone** [dvbsknd/freeCodeCamp-frontEndProjects#4]
https://github.com/dvbsknd/freeCodeCamp-frontEndProjects/blob/eec107c94008e5eee81b0eb59be6cf9b43098b22/challenges/pomodoro-clock/app.js#L181

When passing in props to a component, it's good to think of them as being as benign to a component as possible. The reason for this is that any special logic should be handled prior to send it down the wire. The component's responsibility should be to to just render the output.

In lines 181-185 it's best to just pass in the variables and let the components deal with how they get rendered (in this case, they use a `formatTime` utility function). Make sense?

**Comment by dvbsknd** [comment]
I gotcha—so it would be better to format/process the state somewhere higher up the chain and then just pass the value "ready for rendering" to the component?

**Comment by vitalbone** [comment]
It's sort of logic dependent. If the logic is divorced from the output like if it's calculating or processing something then yes, up high. If it's rendering logic, which in this case it is cause that's really what `formatTime` is doing then the component can handle it.

**Comment by dvbsknd** [comment]
Ah, I got it—I had it the wrong way around. Just pass the _value_ to the component and let the component decide how it wants to format it.
